# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm, Node.js, and dependencies
        uses: pnpm/setup@v3
        with:
          require-lockfile: true
          cache: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Run Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm, Node.js, and dependencies
        uses: pnpm/setup@v3
        with:
          require-lockfile: true
          cache: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Run Typecheck
        run: pnpm run typecheck

  dead-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm, Node.js, and dependencies
        uses: pnpm/setup@v3
        with:
          require-lockfile: true
          cache: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Run Knip
        run: pnpm run knip

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm, Node.js, and dependencies
        uses: pnpm/setup@v3
        with:
          runtime: node@${{ matrix.node-version }}
          require-lockfile: true
          cache: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Run Tests
        run: pnpm run test
